<?php

$title = 'Relevant News';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('news', array('action'=>'add'));?>">Add new News</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Posted</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($news as $item) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($item->title);?></td>
            <td><?php echo $this->escapeHtml($item->content);?></td>
            <td><?php echo $this->escapeHtml($item->posted);?></td>
            <td>
                <a href="<?php echo $this->url('news',
                    array('action'=>'edit', 'id' => $item->id));?>">Edit news</a>
                <a href="<?php echo $this->url('news',
                    array('action'=>'delete', 'id' => $item->id));?>">Delete news</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>